import { DM_Sans, Figtree, Inter, Kumbh_Sans, Roboto, Yuji_Mai } from 'next/font/google';
import './globals.css';
import Navbar from './components/section/Navbar';
import Footer from './components/section/Footer';
import StoreProvider from './StoreProvider';


// Define fonts with their configurations
const roboto = Roboto({ 
  subsets: ['latin'],
  weight: ["300", "400", "500", "700"],
  variable: "--font-roboto",
});

const figtree = Figtree({ 
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-figtree",
});

const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ["400", "500", "700"],
  variable: "--font-dm-sans",
});

const inter = Inter({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-inter",
});

const kumbhSans = Kumbh_Sans({
  subsets: ['latin'],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-kumbh-sans",
});

const yujiMai = Yuji_Mai({
  subsets: ['latin'],
  weight: ["400"], // Yuji Mai typically has a single weight (Regular/400).
  variable: "--font-yuji-mai",
});

export const metadata = {
  title: 'bdcalling',
  description: 'Generated by create next app',
};



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply multiple fonts using their variable classes */}
      <body className={`${roboto.variable} ${figtree.variable} ${dmSans.variable} ${inter.variable} ${kumbhSans.variable} ${yujiMai.variable}`}>
           <StoreProvider>
               <Navbar/>
                {children}
               <Footer/>   
           </StoreProvider>
      </body>
    </html>
  );
}
